const API = location.origin;
const WS = location.protocol === 'https:' ? `wss://${location.host}` : `ws://${location.host}`;
const VERSION = 1;
const state = { profile: JSON.parse(localStorage.getItem('caravan.profile') || 'null') || { name: 'Driver', car: '', person: false, color: '#1769e0' }, saved: JSON.parse(localStorage.getItem('caravan.trips') || '[]'), trip: null, socket: null, members: new Map(), marks: new Map(), routes: new Map(), chat: [], map: null, markers: new Map(), meMarker: null, destinationMarker: null, watch: null, currentLocation: null, reconnect: 0, ptt: false, markMode: false, markTimer: null, navigating: false };
const $ = id => document.getElementById(id); const now = () => Date.now(); const save = () => { localStorage.setItem('caravan.profile', JSON.stringify(state.profile)); localStorage.setItem('caravan.trips', JSON.stringify(state.saved)); }; const toast = text => { $('toast').textContent = text; $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 2600); }; const message = type => ({ type, version: VERSION, timestamp: now() });
function show(view) { document.querySelectorAll('.view').forEach(v => v.classList.add('hidden')); $(view).classList.remove('hidden'); }
function renderProfile() { const p = state.profile; $('profile-card').innerHTML = `<div class="avatar" style="background:${p.color}22;color:${p.color}">${(p.name || 'D')[0].toUpperCase()}</div><div class="profile-copy"><strong>${esc(p.name)}</strong><span class="muted">${p.person ? 'On foot' : esc(p.car || 'Vehicle')}</span></div><span class="muted">Edit</span>`; }
function renderSaved() { const el = $('saved-trips'); $('saved-caption').textContent = state.saved.length ? `${state.saved.length} saved · leave never deletes` : 'Create or join a trip. It stays here until you delete it.'; el.innerHTML = state.saved.length ? state.saved.map((t, i) => `<div class="saved-trip"><div><strong>${esc(t.name || 'Caravan Trip')}</strong><span class="muted">Code: ${esc(t.code)}</span></div><button data-rejoin="${i}">Rejoin</button></div>`).join('') : '<div class="empty">No trips yet.</div>'; el.querySelectorAll('[data-rejoin]').forEach(b => b.onclick = () => joinTrip(state.saved[+b.dataset.rejoin].code, state.saved[+b.dataset.rejoin])); }
function esc(v) { return String(v ?? '').replace(/[&<>"']/g, x => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[x])); }
function openProfile() { $('profile-name').value = state.profile.name; $('profile-car').value = state.profile.car; $('profile-person').checked = state.profile.person; $('profile-dialog').showModal(); }
$('profile-form').onsubmit = e => { e.preventDefault(); state.profile = { ...state.profile, name: $('profile-name').value.trim() || 'Driver', car: $('profile-car').value.trim(), person: $('profile-person').checked }; save(); $('profile-dialog').close(); renderProfile(); };
$('profile-card').onclick = openProfile; $('settings-button').onclick = () => show('settings-view'); $('settings-back').onclick = () => show('home-view'); $('clear-data').onclick = () => { localStorage.clear(); location.reload(); };
let dialogMode = 'create'; $('create-button').onclick = () => { dialogMode = 'create'; $('trip-dialog-title').textContent = 'Create convoy'; $('trip-name-row').classList.remove('hidden'); $('invite-row').classList.add('hidden'); $('trip-name').value = `${state.profile.name}'s Road Trip`; $('trip-dialog').showModal(); }; $('join-button').onclick = () => { dialogMode = 'join'; $('trip-dialog-title').textContent = 'Join convoy'; $('trip-name-row').classList.add('hidden'); $('invite-row').classList.remove('hidden'); $('invite-code').value = ''; $('trip-dialog').showModal(); };
$('trip-form').onsubmit = async e => { e.preventDefault(); try { if (dialogMode === 'create') { const name = $('trip-name').value.trim() || 'Caravan Trip'; const clientId = crypto.randomUUID(); const r = await fetch(`${API}/api/trips`, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ name, clientId, displayName:state.profile.name }) }); if (!r.ok) throw Error('Could not create trip'); const t = await r.json(); state.saved = [{ name:t.name, code:t.inviteCode, tripId:t.tripId, leaderToken:t.leaderToken }, ...state.saved.filter(x => x.tripId !== t.tripId)]; save(); $('trip-dialog').close(); await joinTrip(t.inviteCode, state.saved[0]); } else { const code = $('invite-code').value.trim().toUpperCase(); if (!code) return; $('trip-dialog').close(); await joinTrip(code); } } catch (e) { toast(e.message); } };
async function joinTrip(code, saved = null) { let trip = saved; if (!trip) { const r = await fetch(`${API}/api/trips/lookup`, { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({ inviteCode:code }) }); if (!r.ok) throw Error('Invite code not found'); const found = await r.json(); trip = { code, tripId:found.tripId }; } state.trip = { ...trip, code }; show('trip-view'); $('trip-title').textContent = trip.name || 'Caravan Trip'; $('invite-code-label').textContent = code; $('member-count').textContent = '0'; setupMap(); connect(); }
function setupMap() { if (state.map) return; state.map = new maplibregl.Map({ container:'map', style:'https://tiles.openfreemap.org/styles/liberty', center:[51.389,35.6892], zoom:13, attributionControl:true }); state.map.addControl(new maplibregl.NavigationControl(), 'bottom-right'); const canvas=state.map.getCanvas(); const markFromPixel=(x,y)=>{const point=state.map.unproject([x,y]);placeMark(point.lat,point.lng);state.markMode=false;$('mark-button').classList.remove('active');}; state.map.on('contextmenu', e => placeMark(e.lngLat.lat, e.lngLat.lng)); state.map.on('click', e => { if (state.markMode) markFromPixel(e.point.x,e.point.y); }); state.map.on('touchstart', e => { if (e.originalEvent.touches.length !== 1) return; clearTimeout(state.markTimer); state.markTimer=setTimeout(() => markFromPixel(e.point.x,e.point.y),650); }); state.map.on('touchend', () => clearTimeout(state.markTimer)); state.map.on('touchmove', () => clearTimeout(state.markTimer)); canvas.addEventListener('click', e => { if (!state.markMode) return; const rect=canvas.getBoundingClientRect(); markFromPixel(e.clientX-rect.left,e.clientY-rect.top); }); let touchTimer; canvas.addEventListener('touchstart', e => { if (e.touches.length !== 1) return; const rect=canvas.getBoundingClientRect();const touch=e.touches[0];touchTimer=setTimeout(()=>markFromPixel(touch.clientX-rect.left,touch.clientY-rect.top),650); }, {passive:true}); canvas.addEventListener('touchend',()=>clearTimeout(touchTimer),{passive:true}); canvas.addEventListener('touchmove',()=>clearTimeout(touchTimer),{passive:true}); state.map.on('load', () => renderAll()); }
function connect() { if (!state.trip) return; state.socket?.close(); const url = `${WS}/trip/${encodeURIComponent(state.trip.tripId)}`; state.socket = new WebSocket(url); setStatus('reconnecting'); state.socket.onopen = () => { state.reconnect = 0; setStatus('connected'); send({ ...message('join'), clientId: getClientId(), displayName:state.profile.name, carName:state.profile.person ? undefined : state.profile.car, memberKind:state.profile.person ? 'person' : 'vehicle', avatarColor:state.profile.color, inviteCode:state.trip.code, leaderToken:state.trip.leaderToken }); startLocation(); }; state.socket.onmessage = e => handle(JSON.parse(e.data)); state.socket.onclose = () => { setStatus('reconnecting'); clearTimeout(state.reconnectTimer); state.reconnectTimer = setTimeout(connect, Math.min(10000, 1000 * ++state.reconnect)); }; state.socket.onerror = () => setStatus('reconnecting'); }
function getClientId() { let id = localStorage.getItem('caravan.clientId'); if (!id) { id = crypto.randomUUID(); localStorage.setItem('caravan.clientId', id); } return id; } function send(v) { if (state.socket?.readyState === WebSocket.OPEN) state.socket.send(JSON.stringify(v)); }
function handle(m) { switch(m.type) { case 'joined': if (m.tripId) { state.trip.tripId = m.tripId; } if (m.destination) setDestination(m.destination); renderAll(); break; case 'members_snapshot': (m.members || []).forEach(upsert); renderAll(); break; case 'member_joined': upsert(m.member || m); renderAll(); break; case 'member_left': state.members.delete(m.clientId || m.id); renderAll(); break; case 'location_update': { const old=state.members.get(m.clientId); if(old) { upsert({...old,...m,lastLocationAt:m.timestamp}); renderAll(); } } break; case 'destination_update': setDestination(m); renderAll(); break; case 'destination_clear': clearDestination(); break; case 'map_mark': state.marks.set(m.clientId, m); renderAll(); break; case 'map_mark_clear': state.marks.delete(m.clientId); renderAll(); break; case 'chat_message': addChat(m); break; case 'error': toast(m.message || 'Server error'); break; case 'trip_ended': toast('This convoy has ended'); leaveTrip(); break; } }
function upsert(m) { const id=m.id || m.clientId; if(id) state.members.set(id, {...state.members.get(id), ...m}); } function setStatus(s) { const el=$('connection-status'); el.className=`connection-chip ${s}`; el.querySelector('b').textContent=s==='connected'?'Live':s==='reconnecting'?'Syncing':'Offline'; } function startLocation() { if(state.watch !== null || !navigator.geolocation) return; state.watch=navigator.geolocation.watchPosition(p => send({...message('location_update'), latitude:p.coords.latitude, longitude:p.coords.longitude, accuracy:p.coords.accuracy, speed:p.coords.speed || undefined, heading:p.coords.heading || undefined}), () => toast('Location permission is needed for live position'), { enableHighAccuracy:true, maximumAge:2000 }); }
function stopLocation() { if(state.watch !== null) navigator.geolocation.clearWatch(state.watch); state.watch=null; } function renderAll() { renderMembers(); renderMap(); }
function renderMembers() { const list=[...state.members.values()].sort((a,b)=>(b.isLeader?1:0)-(a.isLeader?1:0)); $('member-count').textContent=Math.max(0,list.length-1); $('fleet-title').textContent=`Convoy (${Math.max(0,list.length-1)} members)`; $('members').innerHTML=list.length ? list.filter(m=>m.id!==getClientId()).map(m=>`<div class="member"><div class="avatar" style="background:${(m.avatarColor||'#1769e0')}22;color:${m.avatarColor||'#1769e0'}">${esc((m.displayName||'D')[0])}</div><div class="member-info"><strong>${esc(m.displayName)} ${m.isLeader?' · Leader':''}</strong><span>${esc(m.carName || (m.memberKind==='person'?'On foot':'Vehicle'))}${m.speed ? ` · ${Math.round(m.speed*3.6)} km/h`:''}</span></div><span class="member-status ${m.connectionStatus||'connected'}"></span></div>`).join('') : '<div class="empty">Waiting for convoy members...</div>'; }
function marker(id, lngLat, color, label, kind='member') { let x=state.markers.get(id); if(!x) { const element=document.createElement('div'); element.className=`caravan-marker ${kind}`; element.innerHTML=kind==='member' ? '<span class="material-symbols-rounded marker-glyph">directions_car</span>' : kind==='mark' ? '<span class="material-symbols-rounded marker-glyph">location_on</span>' : '<span class="material-symbols-rounded marker-glyph">navigation</span>'; x=new maplibregl.Marker({element,anchor:'bottom'}).setLngLat(lngLat).addTo(state.map); state.markers.set(id,x); } else x.setLngLat(lngLat); x.getElement().style.setProperty('--marker-color', color); x.getElement().title=label; }
function renderMap() { if(!state.map || !state.map.loaded()) return; const active=new Set(); state.members.forEach(m=>{ if(Number.isFinite(m.longitude)&&Number.isFinite(m.latitude)){const id=`member:${m.id}`; active.add(id); marker(id,[m.longitude,m.latitude],m.avatarColor||'#1769e0',m.displayName,'member'); }}); state.marks.forEach(m=>{if(Number.isFinite(m.longitude)&&Number.isFinite(m.latitude)){const id=`mark:${m.clientId}`;active.add(id);marker(id,[m.longitude,m.latitude],m.color||'#f59e0b',m.displayName||'Map mark','mark');}}); if(state.destination){active.add('destination');marker('destination',[state.destination.longitude,state.destination.latitude],'#d92d20',state.destination.label||'Destination','destination');} state.markers.forEach((m,id)=>{if(!active.has(id)){m.remove();state.markers.delete(id)}}); }
function placeMark(lat,lng) { const mark={clientId:getClientId(),displayName:state.profile.name,latitude:lat,longitude:lng,color:state.profile.color,updatedAt:now()}; state.marks.set(mark.clientId,mark); if(state.map) marker(`mark:${mark.clientId}`,[lng,lat],mark.color,mark.displayName,'mark'); renderMap(); send({...message('map_mark'), latitude:lat, longitude:lng, color:state.profile.color}); toast('Map mark placed'); } function setDestination(d) { state.destination=d; $('destination-hud').classList.remove('hidden'); $('destination-label').textContent=d.label||'Marked Point'; $('destination-info').textContent='Destination set'; if(state.map) marker('destination',[d.longitude,d.latitude],'#d92d20',d.label||'Destination','destination'); } function clearDestination() { state.destination=null; $('destination-hud').classList.add('hidden'); const m=state.markers.get('destination'); m?.remove(); state.markers.delete('destination'); }
$('destination-header-button').onclick = () => { if(!isLeader()) return toast('Only the leader can set a destination'); const raw=prompt('Destination latitude, longitude, label'); if(!raw)return; const [lat,lng,...label]=raw.split(',').map(x=>x.trim()); if(!Number.isFinite(+lat)||!Number.isFinite(+lng))return toast('Use latitude, longitude'); send({...message('destination_update'),latitude:+lat,longitude:+lng,label:label.join(', '),leaderToken:state.trip.leaderToken}); }; $('mark-button').onclick=()=>{state.markMode=!state.markMode;$('mark-button').classList.toggle('active',state.markMode);toast(state.markMode?'Tap the map to place a mark':'Mark mode cancelled');}; $('locate-button').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>state.map?.flyTo({center:[p.coords.longitude,p.coords.latitude],zoom:16})); $('osrm-button').onclick=routeToDestination; $('neshan-button').onclick=routeToDestination; $('clear-destination').onclick=()=>{if(isLeader())send({...message('destination_clear'),leaderToken:state.trip.leaderToken});clearDestination();}; $('fleet-button').onclick=()=> $('fleet-panel').classList.remove('hidden'); $('fleet-panel').onclick=e=>{if(e.target===$('fleet-panel'))$('fleet-panel').classList.add('hidden')}; $('chat-button').onclick=()=>{if($('chat-sheet').classList.contains('hidden'))$('quick-prompts').classList.toggle('hidden');else $('chat-sheet').classList.remove('hidden');}; $('open-chat-from-prompts').onclick=()=>{$('quick-prompts').classList.add('hidden');$('chat-sheet').classList.remove('hidden');}; $('copy-code').onclick=()=>navigator.clipboard?.writeText(state.trip?.code||'').then(()=>toast('Invite code copied'));
async function routeToDestination() { if(!state.destination)return toast('Set a destination first'); const me=state.members.get(getClientId()); if(!me?.latitude)return toast('Waiting for your location'); const u=`https://router.project-osrm.org/route/v1/driving/${me.longitude},${me.latitude};${state.destination.longitude},${state.destination.latitude}?overview=full&geometries=geojson`; const r=await fetch(u); if(!r.ok)return toast('Route unavailable'); const d=await r.json(); const points=d.routes?.[0]?.geometry?.coordinates||[]; send({...message('route_update'),colorHex:state.profile.color,points:points.map(([lng,lat])=>[lat,lng])}); toast('Route shared with convoy'); }
function isLeader(){return !!state.members.get(getClientId())?.isLeader || !!state.trip.leaderToken} function addChat(m){state.chat.push(m); const el=$('chat-messages'); el.innerHTML=state.chat.map(x=>`<div class="chat-message ${x.clientId===getClientId()?'mine':''}"><small>${esc(x.senderName||'Member')}</small>${esc(x.text)}</div>`).join(''); el.scrollTop=el.scrollHeight; const p=$('message-previews'); p.innerHTML=`<div class="preview"><b>${esc(m.senderName||'Member')}</b><br>${esc(m.text)}</div>`; setTimeout(()=>p.innerHTML='',4000); }
 $('close-chat').onclick=()=>{$('chat-sheet').classList.add('hidden')}; $('chat-form').onsubmit=e=>{e.preventDefault();const input=$('chat-input');const text=input.value.trim();if(text){send({...message('chat_message'),text});addChat({text,senderName:state.profile.name,clientId:getClientId()});input.value='';}}; $('ptt-button').onpointerdown=()=>{state.ptt=true;$('ptt-button').classList.add('active');$('ptt-button').querySelector('b').textContent='TRANSMITTING';$('ptt-button').querySelector('small').textContent='Microphone active (hold or release)';send(message('ptt_request'));}; ['pointerup','pointercancel','pointerleave'].forEach(x=>$('ptt-button').addEventListener(x,()=>{if(state.ptt){state.ptt=false;$('ptt-button').classList.remove('active');$('ptt-button').querySelector('b').textContent='PUSH TO TALK';$('ptt-button').querySelector('small').textContent='Tap to toggle, or hold to talk';send(message('ptt_release'));}})); $('share-button').onclick=()=>navigator.clipboard?.writeText(`${location.origin}/?join=${state.trip.code}`).then(()=>toast('Invite link copied')); $('back-button').onclick=leaveTrip; $('leave-button').onclick=leaveTrip; $('trip-settings-button').onclick=()=>show('settings-view'); $('theme-button').onclick=()=>document.body.classList.toggle('light-cockpit'); $('voice-button').onclick=()=>toast('Voice notes require microphone access'); function leaveTrip(){stopLocation();send(message('leave'));state.socket?.close();state.socket=null;state.trip=null;state.members.clear();state.markers.forEach(m=>m.remove());state.markers.clear();show('home-view');renderSaved();} const params=new URLSearchParams(location.search); if(params.get('join')){setTimeout(()=>{dialogMode='join';$('invite-code').value=params.get('join');$('trip-dialog-title').textContent='Join convoy';$('trip-name-row').classList.add('hidden');$('invite-row').classList.remove('hidden');$('trip-dialog').showModal();},100);} renderProfile();renderSaved();

// A map mark is also a local navigation target, matching the Kotlin "Go to Mark" flow.
const originalPlaceMark = placeMark;
placeMark = function(lat, lng) {
	originalPlaceMark(lat, lng);
	state.destination = { latitude: lat, longitude: lng, label: 'Marked Point', updatedAt: now(), updatedById: getClientId(), updatedByName: state.profile.name };
	setDestination(state.destination);
	routeToDestination();
};
function drawActiveRoute(points) {
	if (!state.map || !state.map.loaded() || points.length < 2) return;
	const data = { type: 'Feature', geometry: { type: 'LineString', coordinates: points } };
	const source = state.map.getSource('active-route');
	if (source) source.setData(data);
	else { state.map.addSource('active-route', { type: 'geojson', data }); state.map.addLayer({ id: 'active-route-line', type: 'line', source: 'active-route', paint: { 'line-color': '#1769e0', 'line-width': 5, 'line-opacity': .9 } }); }
}
routeToDestination = async function() {
	if (!state.destination) return toast('Set a destination first');
	const me = state.currentLocation || state.members.get(getClientId());
	if (!me?.latitude) return toast('Waiting for your location');
	const u = `https://router.project-osrm.org/route/v1/driving/${me.longitude},${me.latitude};${state.destination.longitude},${state.destination.latitude}?overview=full&geometries=geojson`;
	const r = await fetch(u); if (!r.ok) return toast('Route unavailable');
	const d = await r.json(); const points = d.routes?.[0]?.geometry?.coordinates || [];
	drawActiveRoute(points); state.navigating = true; $('destination-info').textContent = 'Navigation active';
	send({...message('route_update'), colorHex:state.profile.color, points:points.map(([lng,lat])=>[lat,lng])}); toast('Navigation started');
};

// Kotlin flow: selecting a point prepares a route; navigation starts only after the explicit button.
startLocation = function() {
	if (state.watch !== null || !navigator.geolocation) return;
	state.watch = navigator.geolocation.watchPosition(p => {
		state.currentLocation = { latitude:p.coords.latitude, longitude:p.coords.longitude };
		send({...message('location_update'), latitude:p.coords.latitude, longitude:p.coords.longitude, accuracy:p.coords.accuracy, speed:p.coords.speed || undefined, heading:p.coords.heading || undefined});
	}, () => toast('Location permission is needed for navigation'), { enableHighAccuracy:true, maximumAge:2000 });
};
const prepareNavigation = routeToDestination;
routeToDestination = async function() {
	state.navigating = false;
	$('start-navigation').classList.add('hidden');
	await prepareNavigation();
	if ($('destination-hud').classList.contains('hidden')) return;
	$('destination-info').textContent = 'Route ready · tap Start navigation';
	$('start-navigation').classList.remove('hidden');
};
$('start-navigation').onclick = () => {
	state.navigating = true;
	$('start-navigation').classList.add('hidden');
	$('destination-info').textContent = 'Navigation active';
	toast('Navigation started');
};
